### ISSUE TITLE
Support Cloning/Generating Identical Secrets for Multiple Fields

### ISSUE THREAD

**Issue by matzegebbe** [aljoshare/runo#358]
It would be beneficial to have the capability to clone or generate the same secret for multiple fields. In scenarios involving Helm charts, specific names for secret keys are often required. Being able to reuse the same secret for different fields (e.g. `password` and `mongodb-root-password`) would simplify the process for me. While it's possible to change references, this approach necessitates code modifications in multiple places in short-lived environments.

Proposed Implementation:

Introduce annotations to specify cloning behavior. For example:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: mongo-db-secrets
  namespace: my-namespace
  labels:
    v1.secret.runo.rocks/managed: "true"
  annotations:
    v1.secret.runo.rocks/generate-0: username

   # clone to value (from key)
    v1.secret.runo.rocks/generate-1: password
    v1.secret.runo.rocks/clone-to-1: mongodb-root-password

    # clone with ref to id 1
    v1.secret.runo.rocks/generate-2: mongodb-root-password
    v1.secret.runo.rocks/clone-from-2: 1

    # comma list for generate
    v1.secret.runo.rocks/generate-1: password,mongodb-root-password

    v1.secret.runo.rocks/generate-3: mongodb-replica-set-key

type: Opaque
data:
```
